# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-01 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consumption', '0001_master_data_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumption',
            name='float_value',
        ),
    ]
